short_name = "Pandemonium Volcano (Small)"
long_name = "Pandemonium Volcano (Small)"
realm = "Great Pandemonium"
item_type = "generic"
is_quest_item = false
is_floor_tile = false
is_global_realm_item = false
is_project_item = false
