short_name = "Pandemonium Stones"
long_name = "Pandemonium Stones"
realm = "Great Pandemonium"
item_type = "generic"
is_quest_item = false
is_floor_tile = false
is_global_realm_item = false
is_project_item = false
