short_name = "Bastion Rift (Horizontal)"
long_name = "Bastion Rift (Horizontal)"
realm = "Bastion of the Void"
item_type = "generic"
is_quest_item = false
is_floor_tile = false
is_global_realm_item = false
is_project_item = false
