short_name = "Bastion Shadow Locker"
long_name = "Bastion Shadow Locker"
realm = "Bastion of the Void"
item_type = "generic"
is_quest_item = false
is_floor_tile = false
is_global_realm_item = false
is_project_item = false
