short_name = "Unsullied Meadows Gems"
long_name = "Unsullied Meadows Gems"
realm = "Unsullied Meadows"
item_type = "generic"
is_quest_item = false
is_floor_tile = false
is_global_realm_item = false
is_project_item = false
