short_name = "Swamplands Lodge"
long_name = "Swamplands Lodge"
realm = "The Swamplands"
item_type = "generic"
is_quest_item = false
is_floor_tile = false
is_global_realm_item = false
is_project_item = false
