short_name = "Reactor Sludge"
long_name = "Reactor Sludge"
realm = "Caustic Reactor"
item_type = "generic"
is_quest_item = false
is_floor_tile = false
is_global_realm_item = false
is_project_item = false
