short_name = "Breakable"
long_name = "Breakable (Temple of Lies)"
realm = "Temple of Lies"
item_type = "Breakable"
is_quest_item = true
is_floor_tile = false
is_global_realm_item = false
is_project_item = false
