short_name = "Temple Cluster (Blue)"
long_name = "Temple Cluster (Blue)"
realm = "Temple of Lies"
item_type = "generic"
is_quest_item = false
is_floor_tile = false
is_global_realm_item = false
is_project_item = false
