short_name = "Blood Grove Tent inner"
long_name = "Blood Grove Tent inner"
realm = "Blood Grove"
item_type = "generic"
is_quest_item = false
is_floor_tile = false
is_global_realm_item = false
is_project_item = false
