short_name = "Blood Grove Stone"
long_name = "Blood Grove Stone"
realm = "Blood Grove"
item_type = "generic"
is_quest_item = false
is_floor_tile = false
is_global_realm_item = false
is_project_item = false
