short_name = "Torture Chamber Parchment"
long_name = "Torture Chamber Parchment"
realm = "Torture Chamber"
item_type = "generic"
is_quest_item = false
is_floor_tile = false
is_global_realm_item = false
is_project_item = false
