short_name = "Dead Ships Statue (Half)"
long_name = "Dead Ships Statue (Half)"
realm = "Dead Ships"
item_type = "Statue"
is_quest_item = false
is_floor_tile = false
is_global_realm_item = false
is_project_item = false
