short_name = "Giant Pandemonium Statue"
long_name = "Giant Pandemonium Statue"
realm = "Great Pandemonium"
item_type = "Statue"
is_quest_item = false
is_floor_tile = false
is_global_realm_item = false
is_project_item = false
