short_name = "Sanctum Umbra Statue (Demon)"
long_name = "Sanctum Umbra Statue (Demon)"
realm = "Sanctum Umbra"
item_type = "Statue"
is_quest_item = false
is_floor_tile = false
is_global_realm_item = false
is_project_item = false
