short_name = "Titan's Wound Effigy"
long_name = "Titan's Wound Effigy"
realm = "Titan's Wound"
item_type = "generic"
is_quest_item = false
is_floor_tile = false
is_global_realm_item = false
is_project_item = false
