short_name = "Gambling Dwarf (Slot Machine)"
long_name = "Gambling Dwarf (Slot Machine)"
item_type = "Utility-NPC"
is_quest_item = false
is_floor_tile = false
is_global_realm_item = false
is_project_item = false
