"""add quest supported and description

Revision ID: 20beeac98e67
Revises: 20f506e71f26
Create Date: 2021-07-10 12:23:42.595352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20beeac98e67'
down_revision = '20f506e71f26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE quest add column description varchar;")
    op.execute("ALTER TABLE quest add column supported BOOLEAN NOT NULL DEFAULT TRUE;")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quest', schema=None) as batch_op:
        batch_op.drop_column('description')
        batch_op.drop_column('supported')

    # ### end Alembic commands ###
