"""Add phash table v2

Revision ID: 20f506e71f26
Revises: 8db658a4acec
Create Date: 2021-07-02 00:03:14.026171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20f506e71f26'
down_revision = '8db658a4acec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sprite_frame_hash',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sprite_frame_id', sa.Integer(), nullable=False),
    sa.Column('floor_sprite_frame_id', sa.Integer(), nullable=False),
    sa.Column('phash', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['floor_sprite_frame_id'], ['sprite_frame.id'], ),
    sa.ForeignKeyConstraint(['sprite_frame_id'], ['sprite_frame.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('floor_sprite_frame_id', 'phash', name='uix_phash_across_floor_tile')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sprite_frame_hash')
    # ### end Alembic commands ###
