"""Add other subclasses of sprites

Revision ID: 220a75208222
Revises: 35f587532cfb
Create Date: 2021-06-02 11:32:21.093189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '220a75208222'
down_revision = '35f587532cfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('creature_sprite',
    sa.Column('sprite_id', sa.Integer(), nullable=False),
    sa.Column('realm_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['realm_id'], ['realm.id'], ),
    sa.ForeignKeyConstraint(['sprite_id'], ['sprite.id'], ),
    sa.PrimaryKeyConstraint('sprite_id'),
    sa.UniqueConstraint('sprite_id')
    )
    with op.batch_alter_table('creature_sprite', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_creature_sprite_realm_id'), ['realm_id'], unique=False)

    op.create_table('enemy_sprite',
    sa.Column('sprite_id', sa.Integer(), nullable=False),
    sa.Column('realm_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['realm_id'], ['realm.id'], ),
    sa.ForeignKeyConstraint(['sprite_id'], ['sprite.id'], ),
    sa.PrimaryKeyConstraint('sprite_id'),
    sa.UniqueConstraint('sprite_id')
    )
    with op.batch_alter_table('enemy_sprite', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_enemy_sprite_realm_id'), ['realm_id'], unique=False)

    op.create_table('npc_sprite',
    sa.Column('sprite_id', sa.Integer(), nullable=False),
    sa.Column('realm_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['realm_id'], ['realm.id'], ),
    sa.ForeignKeyConstraint(['sprite_id'], ['sprite.id'], ),
    sa.PrimaryKeyConstraint('sprite_id'),
    sa.UniqueConstraint('sprite_id')
    )
    with op.batch_alter_table('npc_sprite', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_npc_sprite_realm_id'), ['realm_id'], unique=False)

    op.create_table('wardrobe_sprite',
    sa.Column('sprite_id', sa.Integer(), nullable=False),
    sa.Column('realm_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['realm_id'], ['realm.id'], ),
    sa.ForeignKeyConstraint(['sprite_id'], ['sprite.id'], ),
    sa.PrimaryKeyConstraint('sprite_id'),
    sa.UniqueConstraint('sprite_id')
    )
    with op.batch_alter_table('wardrobe_sprite', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wardrobe_sprite_realm_id'), ['realm_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wardrobe_sprite', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wardrobe_sprite_realm_id'))

    op.drop_table('wardrobe_sprite')
    with op.batch_alter_table('npc_sprite', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_npc_sprite_realm_id'))

    op.drop_table('npc_sprite')
    with op.batch_alter_table('enemy_sprite', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_enemy_sprite_realm_id'))

    op.drop_table('enemy_sprite')
    with op.batch_alter_table('creature_sprite', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_creature_sprite_realm_id'))

    op.drop_table('creature_sprite')
    # ### end Alembic commands ###
