"""Add FloorSprite table

Revision ID: 35f587532cfb
Revises: 737b00dcbc93
Create Date: 2021-05-29 22:01:41.814926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35f587532cfb'
down_revision = '737b00dcbc93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('floor_sprite',
    sa.Column('sprite_id', sa.Integer(), nullable=False),
    sa.Column('realm_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['realm_id'], ['realm.id'], ),
    sa.ForeignKeyConstraint(['sprite_id'], ['sprite.id'], ),
    sa.PrimaryKeyConstraint('sprite_id'),
    sa.UniqueConstraint('sprite_id')
    )
    with op.batch_alter_table('floor_sprite', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_floor_sprite_realm_id'), ['realm_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('floor_sprite', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_floor_sprite_realm_id'))

    op.drop_table('floor_sprite')
    # ### end Alembic commands ###
