"""Add project item sprite subclass

Revision ID: 4c4af8239542
Revises: ad1066cf69a4
Create Date: 2021-06-15 19:26:03.075351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c4af8239542'
down_revision = 'ad1066cf69a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_item_sprite',
    sa.Column('sprite_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sprite_id'], ['sprite.id'], ),
    sa.PrimaryKeyConstraint('sprite_id'),
    sa.UniqueConstraint('sprite_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_item_sprite')
    # ### end Alembic commands ###
