"""add wall subtype

Revision ID: 5f62d10dc9ea
Revises: ab110523bddb
Create Date: 2021-07-23 23:25:18.871380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
from sqlalchemy import orm

from subot import models

revision = '5f62d10dc9ea'
down_revision = 'ab110523bddb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    session = orm.Session(bind=bind)

    op.create_table('wall_sprite',
                    sa.Column('sprite_id', sa.Integer(), nullable=False, primary_key=True),
                    sa.Column('realm_id', sa.Integer(), nullable=False, primary_key=True),
                    sa.ForeignKeyConstraint(['realm_id'], ['realm.id'], ),
                    sa.ForeignKeyConstraint(['sprite_id'], ['sprite.id'], )
    )

    r_type = models.SpriteTypeLookup()
    r_type.id = models.SpriteType.WALL.value
    r_type.name = models.SpriteType.WALL.name

    session.add(r_type)
    session.commit()

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table('wall_sprite')
    op.execute("DELETE FROM sprite_type WHERE id=12;")
