"""Add overlay sprite

Revision ID: 8db658a4acec
Revises: 4c4af8239542
Create Date: 2021-06-21 22:15:04.841418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8db658a4acec'
down_revision = '4c4af8239542'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('overlay_sprite',
    sa.Column('sprite_id', sa.Integer(), nullable=False),
    sa.Column('realm_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['realm_id'], ['realm.id'], ),
    sa.ForeignKeyConstraint(['sprite_id'], ['sprite.id'], ),
    sa.PrimaryKeyConstraint('sprite_id', 'realm_id'),
    sa.UniqueConstraint('realm_id'),
    sa.UniqueConstraint('sprite_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('overlay_sprite')
    # ### end Alembic commands ###
