"""Add master npc sprite subclass

Revision ID: ad1066cf69a4
Revises: 220a75208222
Create Date: 2021-06-10 19:21:53.862017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad1066cf69a4'
down_revision = '220a75208222'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_npc_sprite',
    sa.Column('sprite_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sprite_id'], ['sprite.id'], ),
    sa.PrimaryKeyConstraint('sprite_id'),
    sa.UniqueConstraint('sprite_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('master_npc_sprite')
    # ### end Alembic commands ###
