"""add subclass sprite Chest

Revision ID: c394cca72816
Revises: 5f62d10dc9ea
Create Date: 2021-07-29 14:18:24.977907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
from sqlalchemy import orm

from subot import models

revision = 'c394cca72816'
down_revision = '5f62d10dc9ea'
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    session = orm.Session(bind=bind)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chest_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('chest_sprite',
    sa.Column('sprite_id', sa.Integer(), nullable=False),
    sa.Column('realm_id', sa.Integer(), nullable=True),
    sa.Column('opened', sa.Boolean(), nullable=False),
    sa.Column('chest_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chest_type_id'], ['chest_type.id'], ),
    sa.ForeignKeyConstraint(['realm_id'], ['realm.id'], ),
    sa.ForeignKeyConstraint(['sprite_id'], ['sprite.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sprite_id')
    )

    r_type = models.SpriteTypeLookup()
    r_type.id = models.SpriteType.CHEST.value
    r_type.name = models.SpriteType.CHEST.name

    session.add(r_type)
    session.commit()

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table('chest_sprite')
    op.drop_table('chest_type')

    op.execute("DELETE FROM sprite_type WHERE id=13;")

    # ### end Alembic commands ###
