"""optimize_size_of_phash_table

Revision ID: c7cd192c6c56
Revises: 20beeac98e67
Create Date: 2021-07-18 17:22:36.141532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7cd192c6c56'
down_revision = '20beeac98e67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.get_context().autocommit_block():
        op.execute("""CREATE TABLE sprite_frame_hash_shrunk (
            sprite_frame_id INTEGER NOT NULL,
            floor_sprite_frame_id INTEGER NOT NULL,
            phash INTEGER NOT NULL,
            PRIMARY KEY (floor_sprite_frame_id,phash),
            FOREIGN KEY(floor_sprite_frame_id) REFERENCES sprite_frame (id),
            FOREIGN KEY(sprite_frame_id) REFERENCES sprite_frame (id)
    ) WITHOUT ROWID;""")

        op.execute("""
        INSERT INTO sprite_frame_hash_shrunk(sprite_frame_id, floor_sprite_frame_id, phash) SELECT sprite_frame_id,
               floor_sprite_frame_id, phash FROM sprite_frame_hash;""")
        op.execute("DROP TABLE sprite_frame_hash;")

        op.execute("ALTER TABLE sprite_frame_hash_shrunk RENAME TO sprite_frame_hash;")
        op.execute("VACUUM;")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sprite_frame_hash', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))
        batch_op.create_unique_constraint('uix_phash_across_floor_tile', ['floor_sprite_frame_id', 'phash'])

    # ### end Alembic commands ###
