"""Generate first line of quest title

Revision ID: d62f93d99624
Revises: f7a5c0a8a3cd
Create Date: 2021-05-29 18:15:43.176709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd62f93d99624'
down_revision = 'f7a5c0a8a3cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quest', sa.Column('title_first_line', sa.String(), sa.Computed('CASE\n    WHEN instr(title, "\r\n") > 0\n    THEN substr(title, 0, instr(title, "\r\n"))\n    ELSE title END', ), nullable=False))
    op.create_index(op.f('ix_quest_title_first_line'), 'quest', ['title_first_line'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quest_title_first_line'), table_name='quest')
    op.drop_column('quest', 'title_first_line')
    # ### end Alembic commands ###
