"""sprite offsets + dims

Revision ID: eea64a3f9208
Revises: c394cca72816
Create Date: 2021-12-01 18:18:24.063628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eea64a3f9208'
down_revision = 'c394cca72816'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('sprite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('width_px', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('height_px', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('match_offset_x', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('match_offset_y', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('sprite', schema=None) as batch_op:
        batch_op.drop_column('match_offset_y')
        batch_op.drop_column('match_offset_x')
        batch_op.drop_column('height_px')
        batch_op.drop_column('width_px')

    # ### end Alembic commands ###
