"""Add phash table

Revision ID: f3e7672a9a59
Revises: 8db658a4acec
Create Date: 2021-06-30 21:05:58.531414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3e7672a9a59'
down_revision = '8db658a4acec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sprite_frame_hash',
    sa.Column('floor_sprite_frame_id', sa.Integer(), nullable=False),
    sa.Column('sprite_frame_id', sa.Integer(), nullable=False),
    sa.Column('phash', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['floor_sprite_frame_id'], ['sprite_frame.id'], ),
    sa.ForeignKeyConstraint(['sprite_frame_id'], ['sprite_frame.id'], ),
    sa.PrimaryKeyConstraint('phash'),
    sa.UniqueConstraint('phash')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sprite_frame_hash')
    # ### end Alembic commands ###
