short_name = "Faraway Enclave Pineapple"
long_name = "Faraway Enclave Pineapple"
realm = "Faraway Enclave"
item_type = "generic"
is_quest_item = false
is_floor_tile = false
is_global_realm_item = false
is_project_item = false
