short_name = "Breakable"
long_name = "Breakable (Kingdom of Heretics)"
realm = "Kingdom of Heretics"
item_type = "Breakable"
is_quest_item = true
is_floor_tile = false
is_global_realm_item = false
is_project_item = false
