short_name = "Heretics Bookshelf"
long_name = "Heretics Bookshelf"
realm = "Kingdom of Heretics"
item_type = "generic"
is_quest_item = false
is_floor_tile = false
is_global_realm_item = false
is_project_item = false
