short_name = "Eternity's End Meteor"
long_name = "Eternity's End Meteor"
realm = "Eternity's End"
item_type = "generic"
is_quest_item = false
is_floor_tile = false
is_global_realm_item = false
is_project_item = false
