short_name = "Frostbite Caverns Flag"
long_name = "Frostbite Caverns Flag"
realm = "Frostbite Caverns"
item_type = "generic"
is_quest_item = false
is_floor_tile = false
is_global_realm_item = false
is_project_item = false
