short_name = "The Barrens Ozymandias"
long_name = "The Barrens Ozymandias"
realm = "The Barrens"
item_type = "generic"
is_quest_item = false
is_floor_tile = false
is_global_realm_item = false
is_project_item = false
