short_name = "Cutthroat Jungle Stump"
long_name = "Cutthroat Jungle Stump"
realm = "Cutthroat Jungle"
item_type = "generic"
is_quest_item = false
is_floor_tile = false
is_global_realm_item = false
is_project_item = false
