short_name = "Cutthroat Jungle Log"
long_name = "Cutthroat Jungle Log"
realm = "Cutthroat Jungle"
item_type = "generic"
is_quest_item = false
is_floor_tile = false
is_global_realm_item = false
is_project_item = false
