short_name = "Breakable"
long_name = "Breakable (Path of the Damned)"
realm = "Path of the Damned"
item_type = "Breakable"
is_quest_item = true
is_floor_tile = false
is_global_realm_item = false
is_project_item = false
