short_name = "Path of the Damned Tomb"
long_name = "Path of the Damned Tomb"
realm = "Path of the Damned"
item_type = "generic"
is_quest_item = false
is_floor_tile = false
is_global_realm_item = false
is_project_item = false
