short_name = "Resource Node"
long_name = "Resource Node (Path of the Damned)"
realm = "Path of the Damned"
item_type = "Resource Node"
is_quest_item = true
is_floor_tile = false
is_global_realm_item = false
is_project_item = false
