short_name = "Arachnid Nest Eggs"
long_name = "Arachnid Nest Eggs"
realm = "Arachnid Nest"
item_type = "generic"
is_quest_item = false
is_floor_tile = false
is_global_realm_item = false
is_project_item = false
