short_name = "Blood Grove Mushroom"
long_name = "Blood Grove Mushroom"
realm = "Blood Grove"
item_type = "Plant"
is_quest_item = false
is_floor_tile = false
is_global_realm_item = false
is_project_item = false
