short_name = "Cutthroat Jungle Flower (Yellow)"
long_name = "Cutthroat Jungle Flower (Yellow)"
realm = "Cutthroat Jungle"
item_type = "Plant"
is_quest_item = false
is_floor_tile = false
is_global_realm_item = false
is_project_item = false
