short_name = "Cutthroat Jungle Mushroom"
long_name = "Cutthroat Jungle Mushroom"
realm = "Cutthroat Jungle"
item_type = "Plant"
is_quest_item = false
is_floor_tile = false
is_global_realm_item = false
is_project_item = false
