short_name = "Frostbite Caverns Pine Tree"
long_name = "Frostbite Caverns Pine Tree"
realm = "Frostbite Caverns"
item_type = "Plant"
is_quest_item = false
is_floor_tile = false
is_global_realm_item = false
is_project_item = false
