short_name = "Heretics Flowers"
long_name = "Heretics Flowers"
realm = "Kingdom of Heretics"
item_type = "Plant"
is_quest_item = false
is_floor_tile = false
is_global_realm_item = false
is_project_item = false
