short_name = "Swamplands Flower"
long_name = "Swamplands Flower"
realm = "The Swamplands"
item_type = "Plant"
is_quest_item = false
is_floor_tile = false
is_global_realm_item = false
is_project_item = false
