short_name = "The Barrens Flowers"
long_name = "The Barrens Flowers"
realm = "The Barrens"
item_type = "Plant"
is_quest_item = false
is_floor_tile = false
is_global_realm_item = false
is_project_item = false
