short_name = "Floor Tile"
long_name = "Bastion of the Void Floor Tile"
realm = "Bastion of the Void"
item_type = "Floor Tile"
is_quest_item = false
is_floor_tile = true
is_global_realm_item = false
is_project_item = false
