short_name = "Floor Tile"
long_name = "Refuge of the Magi Floor Tile"
realm = "Refuge of the Magi"
item_type = "Floor Tile"
is_quest_item = false
is_floor_tile = true
is_global_realm_item = false
is_project_item = false
