short_name = "Dead Ships Shipwreck"
long_name = "Dead Ships Shipwreck"
realm = "Dead Ships"
item_type = "generic"
is_quest_item = false
is_floor_tile = false
is_global_realm_item = false
is_project_item = false
