short_name = "Azure Dreams Star"
long_name = "Azure Dreams Star"
realm = "Azure Dream"
item_type = "generic"
is_quest_item = false
is_floor_tile = false
is_global_realm_item = false
is_project_item = false
