short_name = "Resource Node"
long_name = "Resource Node (Sanctum Umbra)"
realm = "Sanctum Umbra"
item_type = "Resource Node"
is_quest_item = true
is_floor_tile = false
is_global_realm_item = false
is_project_item = false
