short_name = "Sanctum Umbra Tithe"
long_name = "Sanctum Umbra Tithe"
realm = "Sanctum Umbra"
item_type = "generic"
is_quest_item = false
is_floor_tile = false
is_global_realm_item = false
is_project_item = false
