short_name = "Refuge Tome Stack"
long_name = "Refuge Tome Stack"
realm = "Refuge of the Magi"
item_type = "generic"
is_quest_item = false
is_floor_tile = false
is_global_realm_item = false
is_project_item = false
